# glopal section contain all the glopal configurations across all of receivers
# as if you have multiple email receivers you will need to repeat some lines over and over
# like smtp configurations, so you can write it here once and it will be pulled from here
global:
route:
  receiver: 'slack'
  group_by: ['alertname']
# How long to initially wait to send a notification for a group
# of alerts. Allows to wait for an inhibiting alert to arrive or collect
# more initial alerts for the same group. (Usually ~0s to few minutes.)
  group_wait: 10s
# How long to wait before sending a notification about new alerts that
# are added to a group of alerts for which an initial notification has
# already been sent. (Usually ~5m or more.)
  group_interval: 15s
# How long to wait before sending a notification again if it has already
# been sent successfully for an alert. (Usually ~3h or more).
  # repeat_interval: 45s

receivers:
- name: 'slack'
  slack_configs:
  - channel: "#prometheus"
    send_resolved: true
    api_url: 'https://hooks.slack.com/services/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'
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}

